#!/usr/bin/env python3
"""
Deflate index.html into an editable skeleton.

index.html is a 5.3 MB single-file build with every image and font inlined as a
data URI. Hand editing it is impractical and risky, so this script swaps every
data URI payload for a {{DU_n}} token and writes:

    v2/skeleton.html   the editable page (about 0.5 MB)
    v2/assets.json     token -> original "data:...;base64,...." string
    v2/asset_index.md  what each token is, guessed from its surrounding context

The root index.html is never modified.
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
SRC = HERE / "index.html"
OUT = HERE / "v2"

DU_RE = re.compile(r"data:[a-zA-Z0-9/+.-]+;base64,[A-Za-z0-9+/=]+")


def context_for(html: str, start: int, end: int) -> str:
    """A short human description of what this data URI is attached to."""
    before = html[max(0, start - 600):start]
    after = html[end:end + 300]

    # font-face
    fam = None
    ff = before.rfind("@font-face")
    if ff != -1 and (start - (max(0, start - 600) + ff)) < 600:
        m = re.search(r"font-family:\s*['\"]?([^;'\"}]+)", before[ff:])
        w = re.search(r"font-weight:\s*(\d+)", before[ff:])
        sty = re.search(r"font-style:\s*(\w+)", before[ff:])
        fam = "@font-face %s%s%s" % (
            m.group(1).strip() if m else "?",
            " w" + w.group(1) if w else "",
            " " + sty.group(1) if sty else "",
        )
    if fam:
        return fam

    # img tag: pull alt / class / id from the enclosing tag
    lt = before.rfind("<")
    if lt != -1:
        tag = before[lt:] + after
        name = re.match(r"<([a-zA-Z0-9-]+)", tag)
        bits = []
        if name:
            bits.append(name.group(1))
        for attr in ("id", "class", "alt", "data-plan", "data-name"):
            m = re.search(attr + r'="([^"]{0,90})"', tag)
            if m:
                bits.append('%s="%s"' % (attr, m.group(1)))
        if bits:
            return " ".join(bits)

    # css background
    if "background" in before[-200:]:
        sel = re.findall(r"([#.\w\[\]-]+)\s*\{[^{}]*$", before)
        return "css background %s" % (sel[-1] if sel else "")

    return "unknown, preceded by: ..." + re.sub(r"\s+", " ", before[-70:])


def main() -> int:
    html = SRC.read_text(encoding="utf-8")
    OUT.mkdir(exist_ok=True)

    assets = {}
    index_rows = []
    n = 0
    out_parts = []
    pos = 0

    for m in DU_RE.finditer(html):
        token = "{{DU_%d}}" % n
        payload = m.group(0)
        assets[token] = payload
        mime = payload.split(";", 1)[0][5:]
        index_rows.append(
            (token, mime, len(payload), context_for(html, m.start(), m.end()))
        )
        out_parts.append(html[pos:m.start()])
        out_parts.append(token)
        pos = m.end()
        n += 1

    out_parts.append(html[pos:])
    skeleton = "".join(out_parts)

    (OUT / "skeleton.html").write_text(skeleton, encoding="utf-8")
    (OUT / "assets.json").write_text(json.dumps(assets), encoding="utf-8")

    lines = [
        "# Asset index (generated by tools/deflate.py)",
        "",
        "%d data URIs extracted from index.html." % n,
        "",
        "| Token | MIME | Size (KB) | Context |",
        "|---|---|---|---|",
    ]
    for token, mime, size, ctx in index_rows:
        ctx = ctx.replace("|", "/").strip()
        lines.append(
            "| `%s` | %s | %.1f | %s |" % (token, mime, size / 1024.0, ctx)
        )
    (OUT / "asset_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("source    %.1f KB" % (len(html.encode()) / 1024))
    print("skeleton  %.1f KB" % (len(skeleton.encode()) / 1024))
    print("assets    %d tokens" % n)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
